### ISSUE TITLE
Switzerland/Vatican squared flags

### ISSUE THREAD

**Issue by mentalstring** [kreativekorp/vexillo#5]
On the process of transitioning from the famfamfam set to Kreative Vexillo, one of things that stood out is that Switzerland's flag is no longer showing as being square.

I realize that the goal is to make all flags being uniform in size (and there's even a set for keeping the original ratio). But, there's a counter-example: that doesn't seem to happen with Nepal's flag, which keeps the non-flag area fully transparent as to keep its shape: its not just stretched out (albeit, admittedly, Nepal is really a special case).

Looking at Apple's and Twitter [emojis](https://emojipedia.org/flag-switzerland/), they seem to keep that flag square-ish too. And while writing this, I learned that the same applies to Vatican's flag as it's also square.

Anyhow, I'm not sure if in Kreative Vexillo this is by design or if there's something that can be done. Either way, it's not a big issue, but thought of reporting it nonetheless.

**Comment by RebeccaRGB** [comment]
This is intentional. When the flag allows for an arbitrary ratio, you still have the choice to use a uniform size or use a square ratio for square flags. If the flag is forced to be square, there is no way to use a uniform size if that is what you want.

Nepal is very much a special case because its construction does not allow for it to be stretched at all. Emoji font vendors all seem to have agreed upon handling this by centering it, but this is arbitrary; it could also be left-aligned (so it's not floating in midair when shown next to a flagpole) or [against a white background](https://en.wikipedia.org/wiki/Flag_of_Nepal#/media/File:Flag_of_Nepal_(white_background,_aspect_ratio_3-2).svg).
